insert into interests(interest_name) values ('Готовка');
insert into interests(interest_name) values ('Чтение');
insert into interests(interest_name) values ('Путешествия');
insert into interests(interest_name) values ('Фотография');
insert into interests(interest_name) values ('Горные лыжи');
insert into interests(interest_name) values ('Велосипедные прогулки');
insert into interests(interest_name) values ('Рыбалка');
insert into interests(interest_name) values ('Пение');
insert into interests(interest_name) values ('Рисование');
insert into interests(interest_name) values ('Флористика');
insert into interests(interest_name) values ('Вязание');
insert into interests(interest_name) values ('Гонки на дронах');
insert into interests(interest_name) values ('Скалолазание');
insert into interests(interest_name) values ('Комиксы и графические романы');
insert into interests(interest_name) values ('Плавание');
insert into interests(interest_name) values ('Театр');
insert into interests(interest_name) values ('Скульптура');
insert into interests(interest_name) values ('Виноделие');
insert into interests(interest_name) values ('Путешествия на кемпере');
insert into interests(interest_name) values ('Садоводство');
insert into interests(interest_name) values ('Музыкальное производство');
insert into interests(interest_name) values ('Водные виды спорта (серфинг, вейкбординг)');
insert into interests(interest_name) values ('Йога');
insert into interests(interest_name) values ('Астрономия');
insert into interests(interest_name) values ('Психология');
insert into interests(interest_name) values ('Аквариумистика');
insert into interests(interest_name) values ('Ботаника');
insert into interests(interest_name) values ('Геокешинг');
insert into interests(interest_name) values ('Реставрация мебели');
insert into interests(interest_name) values ('Граффити');
insert into interests(interest_name) values ('Фехтование');
insert into interests(interest_name) values ('Гольф');
insert into interests(interest_name) values ('Исследование дикой природы');
insert into interests(interest_name) values ('Астрофотография');
insert into interests(interest_name) values ('Собирание монет');
insert into interests(interest_name) values ('Танцы');
insert into interests(interest_name) values ('Футбол');
insert into interests(interest_name) values ('Часы и механизмы');
insert into interests(interest_name) values ('Моделирование (самолеты, корабли и др.)');
insert into interests(interest_name) values ('Бег');
insert into interests(interest_name) values ('Фехтование');
insert into interests(interest_name) values ('Верховая езда');
insert into interests(interest_name) values ('Самосовершенствование');
insert into interests(interest_name) values ('Спортивный туризм');
insert into interests(interest_name) values ('Походы в горы');
insert into interests(interest_name) values ('Настольные игры');
insert into interests(interest_name) values ('Ролевые игры (D&D и др.)');
insert into interests(interest_name) values ('Компьютерные игры');